### ISSUE TITLE
Container max width issues

### ISSUE THREAD

**Issue by sambaldwin** [sb-ph/portfolio-starter#30]
Add something like:

```css

.site-header,
.site-main,
.site-footer {
  margin-left: auto;
  margin-right: auto;
  max-width: var(--width-container);
  width: 100%;
}

```
